---
# Ansible playbook to install and configure Jenkins on Ubuntu EC2 instance
- name: Install and Configure Jenkins on Ubuntu EC2
  hosts: all  # Define this group in your inventory
  become: true  # Use sudo privileges
  vars:
    jenkins_port: 8080

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install dependencies
      apt:
        name:
          - openjdk-11-jdk
          - apt-transport-https
          - gnupg
        state: present

    - name: Add Jenkins repository key
      shell: |
        mkdir -p /etc/apt/keyrings
        curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee /etc/apt/keyrings/jenkins-keyring.asc > /dev/null
      args:
        warn: false
      check_mode: false

    - name: Add Jenkins repository
      shell: |
        echo "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/" | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
      args:
        warn: false
      check_mode: false

    - name: Update apt cache after adding Jenkins repository
      apt:
        update_cache: yes
      check_mode: false

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
      notify: restart jenkins

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: Wait for Jenkins to start up
      wait_for:
        port: "{{ jenkins_port }}"
        delay: 10
        timeout: 300

    - name: Get Jenkins initial admin password
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_admin_password
      changed_when: false

    - name: Display Jenkins initial admin password
      debug:
        msg: "Jenkins initial admin password: {{ jenkins_admin_password.stdout }}"

    - name: Configure Jenkins firewall
      ufw:
        rule: allow
        port: "{{ jenkins_port }}"
        proto: tcp

    - name: Allow SSH through firewall
      ufw:
        rule: allow
        port: 22
        proto: tcp

    - name: Enable UFW
      ufw:
        state: enabled
        policy: deny
  handlers:
    - name: restart jenkins
      service:
        name: jenkins
        state: restarted
