---
- name: Install Jenkins and Terraform
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - wget
          - apt-transport-https
          - gnupg2
        state: present

    - name: Install fontconfig and openjdk-21-jre
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - fontconfig
        - openjdk-21-jre

    - name: Wait for 30 seconds before installing Jenkins
      pause:
        seconds: 30
        echo: no

    - name: Check Java version
      command: java -version
      register: java_version
      ignore_errors: yes

    - name: Download Jenkins keyring
      get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /etc/apt/keyrings/jenkins-keyring.asc
        mode: '0644'

    - name: Add Jenkins apt repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
               /etc/apt/sources.list.d/jenkins.list > /dev/null"
        state: present
        filename: jenkins

    - name: Update apt cache after adding Jenkins repo
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
        force: yes
    - name: Wait for 30 seconds after Jenkins installation
      pause:
        seconds: 30
        echo: no
    - name: Wait for 30 seconds before installing Terraform
      pause:
        seconds: 30
        echo: no
  

    - name: Download Terraform zip
      get_url:
        url: https://releases.hashicorp.com/terraform/1.6.5/terraform_1.6.5_linux_386.zip
        dest: /tmp/terraform_1.6.5_linux_386.zip
        mode: '0644'

    - name: Install unzip
      apt:
        name: unzip
        state: present

    - name: Unzip Terraform
      unarchive:
        src: /tmp/terraform_1.6.5_linux_386.zip
        dest: /usr/local/bin/
        remote_src: yes
        mode: '0755'
        creates: /usr/local/bin/terraform
